-- DROP TABLE IF EXISTS genres CASCADE;
-- DROP TABLE IF EXISTS MPA CASCADE;

CREATE TABLE IF NOT EXISTS users (
                                     user_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name varchar NOT NULL,
                                     birthdate timestamp NOT NULL,
                                     email varchar NOT NULL,
                                     login varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS friendship (
                                          user_id1 int,
                                          user_id2 int,
                                          status_id boolean,
                                          PRIMARY KEY (user_id1, user_id2),
                                          CONSTRAINT from_fk FOREIGN KEY (user_id1) REFERENCES users (user_id) ON DELETE CASCADE,
                                          CONSTRAINT to_fk FOREIGN KEY (user_id2) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS genres (
                                      id INTEGER NOT NULL PRIMARY KEY,
                                      name varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS MPA (
                                   id INTEGER NOT NULL PRIMARY KEY,
                                   name varchar NOT NULL,
                                   description varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS films (
                                       film_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       name varchar NOT NULL,
                                       description varchar NOT NULL,
                                       release_date timestamp NOT NULL,
                                       duration int NOT NULL,
                                       MPA_id int NOT NULL,
                                       CONSTRAINT mpa_fk FOREIGN KEY (MPA_id) REFERENCES MPA (id)
);



CREATE TABLE IF NOT EXISTS film_genre (
                                            film_id int,
                                            genre_id int,
                                            PRIMARY KEY (film_id, genre_id),
                                            CONSTRAINT films_fk FOREIGN KEY (film_id) REFERENCES films (film_id),
                                            CONSTRAINT genres_fk FOREIGN KEY (genre_id) REFERENCES genres (id)
);





CREATE TABLE IF NOT EXISTS likes (
                                       film_id int,
                                       user_id int,
                                       PRIMARY KEY (film_id, user_id),
                                       CONSTRAINT film_fk FOREIGN KEY (film_id) REFERENCES films (film_id),
                                       CONSTRAINT user_fk FOREIGN KEY (user_id) REFERENCES users (user_id)
);




